### ISSUE TITLE
suggestion - make article title's bold  

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#19]
V 3 article titles are bold and slightly bigger which makes them stand out and draws your attention straight away. V4 is smaller and not that different from the main text. Can we try something similar to V3? also just a quick question - is v4 and v3 the same font just smaller? The v3 font is great - its similar to what Facebook is using (just from the look of things) which works nicely

**Comment by getwes** [comment]
@Lesley2 @SBroomhead 

V3 uses this font scheme: 
> Helvetica, Arial and Sans-serif

V4 uses this font scheme ( like facebooks )
> "Helvetica Neue", Helvetica, Arial and Sans-serif

The font size has changed to be a tad smaller. 

Im happy to make titles bold and bigger if need be. otherwise im not too interested in changing the font as it carries through all aspects of the system. which could cause issues. 

Please let me know.

**Comment by SBroomhead** [comment]
@getwes I agree with @Lesley2 on this. While social media goes smaller, the trend in more media related sites, including LinkedIn seems to be for big titles and big pictures. We need to find our balance. For now I think we are on the big side. As users start interacting extensively with content (which they obviously aren't yet) I suspect we will gradually shift smaller.
