### ISSUE TITLE
suggestion - tags in articles on home page 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#27]
As ehna expands, we will be adding more and more tags to articles - e.g. what country/countries the article is about, orgs, initiative, and all the normal tags. The lists can get long and expand the article size making each article size different - could we have a small tags option in the line with "views" "date" and authors name so that people can click on it to see which tags have been used in the article, but hide the actual tag name in the home view so that all articles look the same. does that make sense?

**Comment by getwes** [comment]
@SBroomhead @Lesley2 i have noticed this before especially with countries before i removed their tags on the tiles. that some tiles were huge and others small due to the amount of tags. 

How ever in saying that. the tags on tiles is a v4 feature. it shows something new to the user. a first off glance that this article already have x-amount of tags. Should be rather limit the amount of tags and only show the latest added. 

Shall we limit the tags on articles feed tiles to 4. and show the latest. and apon entering the article view they then see the full amount of tags.
