### ISSUE TITLE
Bug - Newsletter link doesn't open 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#3]
Newsletter link on home page in the left panel doesn't open

**Comment by SBroomhead** [comment]
@getwes shall we drop the newsletter until v4 is up? Then it's easy to add it and add notifications.

**Comment by getwes** [comment]
@SBroomhead im happy to remove "temporarily" until v4 is up. my suggestion would be that instead of having our own to keep up to date with. i will just link to MailChimp's API. so when newsletters are send or created that side. it will automatically keep our page updated. i think our small issue comes in is trying to keep mailchimp and our side up to date. but having an auto API webhook feeding eHNA would be good.
