### ISSUE TITLE
Bug - Help link doesn't open 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#4]
The Help option on home page in the left column doesn't work

**Comment by getwes** [comment]
eHNA v4 is contains more functionality compared to v3. 
Should the help centre be as basic as v3 or do we need help content for users?

- [ ] How do i register?
- [ ] What happens if i forget my password?
- [ ] How do i favorite content?
- [ ] How do i find my favorites

These are some of the basics when handling users?
Thoughts? @Lesley2  @SBroomhead

**Comment by Lesley2** [comment]
Good idea @getwes  - we probably need to expand the section to incorporate the extra functionality. But we also need to keep it simple and easy to use. I like the examples you suggested 
@SBroomhead

**Comment by getwes** [comment]
I think we need to expand. @Lesley2 - i will get all the other issues handled on this list. and near the end just before we ready to go live. ill handle a "help centre" upgrade. i think the most important thing now is to get all issues sorted.
