### ISSUE TITLE
Suggestion - remove tags under "People" "initiatives" and "organisations" 

### ISSUE THREAD

**Issue by Lesley2** [Acfee/ehna-dev#5]
Just an observation - people, initiatives and organisations have tags showing under each. While I see the value in being able to see which tags are being used for each, the lists of tags could get quite long, meaning that the space used for each person, org and initiate profile could expand and will differ for each. This means they aren't uniform which looks a bit strange and has means some have wasted space

**Comment by SBroomhead** [comment]
@Lesley2 they aren't actually tags, but rather hyperlinks to other sections in eHNA. Your point raises a few things for me. Firstly, we need to make an eHNA link look different to a Tag, because they have a different role. Could Tags be grey and eHNA links be the same look but with a thin blue border line? Secondly, the ones on the People list don't work, because they are jobs and don't actually link to pages in eHNA like the eHNA links on the Orgs list or Inittaives list. SO I suggest removing the links on the People list, until we have added the skills lists, at which point those would be the perfect eHNA links, because we're going to have a new page in v5 called Capabilities which will have lists of skills and knowledge. I hope that helps.

**Comment by getwes** [comment]
@Lesley2 @SBroomhead could we make a final decision for this issue and finalise on the website? shall we keep the new tag idea in the feed tile for articles only for the launch on v4. and then look at this issue again at a later stage?

**Comment by getwes** [comment]
@Lesley2 @SBroomhead All tags on tiles except articles has been removed.
